server:
  adminAPI:
    enabled: true
  adminCredentials:
    username: cerbos
    passwordHash: <bcrypt-hash>
  httpListenAddr: ":3592"
  grpcListenAddr: ":3593"
storage:
  driver: "disk"
  disk:
    directory: /policies